# Car Evaluation 🚗 2.5 (McQueen Edition)
   
## Lab Seven: Wide and Deep Network Architectures
   
### Justin Ledford, Luke Wood, Traian Pop

In [119]:
%matplotlib inline
import numpy as np
import plotly
import pandas as pd
import matplotlib.pyplot as plt
import time
import sys
import requests

import warnings
warnings.filterwarnings('ignore')

## Dataset Selection

Select a dataset identically to lab one. That is, the dataset must be table data. In terms of generalization performance, it is helpful to have a large dataset for building a wide and deep network. It is also helpful to have many different categorical features to create the embeddings and cross-product embeddings. It is fine to perform binary classification or multi-class classification.
https://archive.ics.uci.edu/ml/machine-learning-databases/adult/

___ 

## Preparation (40 points total)
   
### [10 points] Define and prepare your class variables. Use proper variable representations (int, float, one-hot, etc.). Use pre-processing methods (as needed) for dimensionality reduction, scaling, etc. Remove variables that are not needed/useful for the analysis. Describe the final dataset that is used for classification/regression (include a description of any newly formed variables you created). 
   
### [10 points] Identify groups of features in your data that should be combined into cross-product features.
   
### [10 points] Choose and explain what metric(s) you will use to evaluate your algorithm’s performance. You should give a detailed argument for why this (these) metric(s) are appropriate on your data. That is, why is the metric appropriate for the task (e.g., in terms of the business case for the task). Please note: rarely is accuracy the best evaluation metric to use. Think deeply about an appropriate measure of performance.
   
### [10 points] Choose the method you will use for dividing your data into training and testing (i.e., are you using Stratified 10-fold cross validation? Shuffle splits? Why?). Explain why your chosen method is appropriate or use more than one method as appropriate. Convince me that your cross validation method is a realistic mirroring of how an algorithm would be used in practice. 
___

In [120]:
import pandas as pd
import numpy as np
import requests


# Get column names
r = requests.get('https://raw.githubusercontent.com/LukeWoodSMU/WillBeRenamed/master/col_names.txt')

if r.status_code == 200:
    columns = r.text.split('\n')[:-1]
else:
    print('Error loading column names')

In [121]:
print(columns)

['age', 'class of worker', 'industry code', 'occupation code', 'education', 'wage per hour', 'enrolled in edu inst last wk', 'marital status', 'major industry code', 'major occupation code', 'race', 'hispanic origin', 'sex', 'member of a labor union', 'reason for unemployment', 'full or part time employment stat', 'capital gains', 'capital losses', 'dividends from stocks', 'tax filer status', 'region of previous residence', 'state of previous residence', 'detailed household and family stat', 'detailed household summary in household', 'migration code-change in msa', 'migration code-change in reg', 'migration code-move within reg', 'live in this house 1 year ago', 'migration prev res in sunbelt', 'num persons worked for employer', 'family members under 18', 'country of birth father', 'country of birth mother', 'country of birth self', 'citizenship', 'own business or self employed', "fill inc questionnaire for veteran's admin", 'veterans benefits', 'weeks worked in year', 'year', 'income'

In [122]:
df_train = pd.read_csv(
        'https://archive.ics.uci.edu/ml/machine-learning-databases/census-income-mld/census-income.data.gz',
        compression='gzip', header=None, index_col=False)


df_test = pd.read_csv(
        'https://archive.ics.uci.edu/ml/machine-learning-databases/census-income-mld/census-income.test.gz',
        compression='gzip', header=None, index_col=False)


# Remove weight columns
df_train.drop(24, 1, inplace=True)
df_test.drop(24, 1, inplace=True)

df_train.columns = columns
df_test.columns = columns

# Remove rows with missing data and reset index
df_train.replace(to_replace=' ?',value=np.nan, inplace=True)
df_train.dropna(inplace=True)
df_train.reset_index()

df_test.replace(to_replace=' ?',value=np.nan, inplace=True)
df_test.dropna(inplace=True)
df_test.reset_index()

df_train.head()

age                  class of worker  industry code  occupation code  \
1   58   Self-employed-not incorporated              4               34   
3    9                  Not in universe              0                0   
4   10                  Not in universe              0                0   
6   42                          Private             34                3   
9   34                          Private              4               37   

                     education  wage per hour enrolled in edu inst last wk  \
1   Some college but no degree              0              Not in universe   
3                     Children              0              Not in universe   
4                     Children              0              Not in universe   
6   Bachelors degree(BA AB BS)              0              Not in universe   
9   Some college but no degree              0              Not in universe   

                     marital status                 major industry code  \
1                          Divorced                        Construction   
3                     Never married         Not in universe or children   
4                     Never married         Not in universe or children   
6   Married-civilian spouse present   Finance insurance and real estate   
9   Married-civilian spouse present                        Construction   

                    major occupation code    ...     country of birth father  \
1     Precision production craft & repair    ...               United-States   
3                         Not in universe    ...               United-States   
4                         Not in universe    ...               United-States   
6          Executive admin and managerial    ...               United-States   
9   Machine operators assmblrs & inspctrs    ...               United-States   

  country of birth mother country of birth self  \
1           United-States         United-States   
3           United-States         United-States   
4           United-States         United-States   
6           United-States         United-States   
9           United-States         United-States   

                          citizenship own business or self employed  \
1   Native- Born in the United States                             0   
3   Native- Born in the United States                             0   
4   Native- Born in the United States                             0   
6   Native- Born in the United States                             0   
9   Native- Born in the United States                             0   

  fill inc questionnaire for veteran's admin  veterans benefits  \
1                            Not in universe                  2   
3                            Not in universe                  0   
4                            Not in universe                  0   
6                            Not in universe                  2   
9                            Not in universe                  2   

   weeks worked in year  year     income  
1                    52    94   - 50000.  
3                     0    94   - 50000.  
4                     0    94   - 50000.  
6                    52    94   - 50000.  
9                    52    94   - 50000.  

[5 rows x 41 columns]

In [123]:
# Process data:

# check income values consistent (only 2 values)

# replace categorical with one hot encoding
# scale continuous

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler

labels = dict() 

r = requests.get('https://raw.githubusercontent.com/LukeWoodSMU/WillBeRenamed/master/categorical.txt')
categorical_labels = r.text.split('\n')[:-1]
print(categorical_labels)

for col in categorical_labels + ['income']:
    # strip extra space in strings
    if df_train[col].dtype == 'object':
        df_train[col] = df_train[col].str.strip()
    if df_test[col].dtype == 'object':
        df_test[col] = df_test[col].str.strip()
        
    # convert to ints for one hot encoder to work
    
    # keep labels for reference 
    labels[col] = list(set(df_train[col].unique()) | set(df_test[col].unique()))
    
    df_train[col].replace(to_replace=labels[col],
                            value=np.arange(len(labels[col])),
                            inplace=True)
    df_test[col].replace(to_replace=labels[col],
                            value=np.arange(len(labels[col])),
                            inplace=True)
    
    
r = requests.get('https://raw.githubusercontent.com/LukeWoodSMU/WillBeRenamed/master/continuous.txt')
continuous_labels = r.text.split('\n')[:-1]


for col in continuous_labels:
    df_train[col] = df_train[col].astype(np.float32)
    df_test[col] = df_test[col].astype(np.float32)
    
    ss = StandardScaler()
    df_train[col] = ss.fit_transform(df_train[col].values.reshape(-1, 1))
    df_test[col] = ss.transform(df_test[col].values.reshape(-1, 1))

['class of worker', 'industry code', 'occupation code', 'education', 'enrolled in edu inst last wk', 'marital status', 'major industry code', 'major occupation code', 'race', 'hispanic origin', 'sex', 'member of a labor union', 'reason for unemployment', 'full or part time employment stat', 'tax filer status', 'region of previous residence', 'state of previous residence', 'detailed household and family stat', 'detailed household summary in household', 'migration code-change in msa', 'migration code-change in reg', 'migration code-move within reg', 'live in this house 1 year ago', 'migration prev res in sunbelt', 'family members under 18', 'country of birth father', 'country of birth mother', 'country of birth self', 'citizenship', 'own business or self employed', "fill inc questionnaire for veteran's admin", 'veterans benefits', 'year']


In [124]:
import tensorflow as tf
from tensorflow.contrib import learn
from tensorflow.contrib import layers
from tensorflow.contrib.learn.python import SKCompat
from tensorflow.contrib.learn.python.learn.estimators import model_fn as model_fn_lib
tf.logging.set_verbosity(tf.logging.WARN) # control the verbosity of tensor flow

In [46]:
# Let's start with the TF example (manipulated to work with new syntax)
# https://www.tensorflow.org/tutorials/wide_and_deep
def process_input(df, label_header, categ_headers, numeric_headers):
    # input: what ever you need it to be
    # output: (dict of feature columns as tensors), (labels as tensors)
    
    # ========Process Inputs=========
    # Creates a dictionary mapping from each continuous feature column name (k) to
    # the values of that column stored in a constant Tensor.
    continuous_cols = {k: tf.expand_dims( # make it a column vector
                            tf.cast( # cast to a float32
                                tf.constant(df[k].values), 
                                tf.float32), 
                            1)
                       for k in numeric_headers}
    
    # Creates a dictionary mapping from each categorical feature column name (k)
    # to the values of that column stored as constant Tensors (numeric)
    # then use tensor flow to one hot encode them using the given number of classes 
    # name of encoder is **_int need to map only to **
    categorical_cols = {k: tf.one_hot(indices=tf.constant(df[k].values),
                                      depth=len(labels[k])) 
                        for k in categ_headers}
    
    # Merges the two dictionaries into one.
    feature_cols = dict(continuous_cols)
    feature_cols.update(categorical_cols)
    
    # Convert the label column into a constant Tensor.
    label = None
    if label_header is not None:
        label = tf.constant(df[label_header].values)
        
    return feature_cols, label

In [47]:
process_input(df_train,'income',categorical_labels, continuous_labels)

({'age': <tf.Tensor 'ExpandDims_21:0' shape=(95130, 1) dtype=float32>,
  'capital gains': <tf.Tensor 'ExpandDims_23:0' shape=(95130, 1) dtype=float32>,
  'capital losses': <tf.Tensor 'ExpandDims_24:0' shape=(95130, 1) dtype=float32>,
  'citizenship': <tf.Tensor 'one_hot_130:0' shape=(95130, 5) dtype=float32>,
  'class of worker': <tf.Tensor 'one_hot_102:0' shape=(95130, 9) dtype=float32>,
  'country of birth father': <tf.Tensor 'one_hot_127:0' shape=(95130, 40) dtype=float32>,
  'country of birth mother': <tf.Tensor 'one_hot_128:0' shape=(95130, 40) dtype=float32>,
  'country of birth self': <tf.Tensor 'one_hot_129:0' shape=(95130, 41) dtype=float32>,
  'detailed household and family stat': <tf.Tensor 'one_hot_119:0' shape=(95130, 38) dtype=float32>,
  'detailed household summary in household': <tf.Tensor 'one_hot_120:0' shape=(95130, 8) dtype=float32>,
  'dividends from stocks': <tf.Tensor 'ExpandDims_25:0' shape=(95130, 1) dtype=float32>,
  'education': <tf.Tensor 'one_hot_105:0' sha

In [48]:
# update the model to take input features as a dictionary
def MLP(dict_features, targets, mode):
    # the prototype for this function is as follows
    # input:  (features, targets) 
    # output: (predictions, loss, train_op)
    
    #=======DECODE FEATURES================
    # now let's combine the tensors from the input dictionary
    # into a list of the feature columns
    features = [dict_features[x] for x in continuous_labels+categorical_labels]
   
    # also add in the one hot encoded features
    for col in categorical_labels:
        features.append(dict_features[col])
    
    # now we can just combine all the features together
    features = tf.concat(values=features,axis=1)
    
    # =====SETUP ARCHITECTURE=====
    # we can use functions from learn to add layers and complexity to the model
    # pass features through one hidden layer with relu activation
    features = layers.relu(features, num_outputs=50) 
    # now pass the features through a fully connected layer
    features = layers.fully_connected(features, num_outputs=1) 
    # and pass them through a sigmoid activation
    output_layer = tf.sigmoid(features) 
    # reshape the output to be one dimensional
    predictions = tf.reshape(output_layer, [-1])
    
    # depending on the mode, we may not want to evaluate these
    loss_mse = None
    train_op = None
    
    # Calculate Loss (for both TRAIN and EVAL modes)
    if mode != learn.ModeKeys.INFER:
        # =====LOSS=======
        # we want to use MSE as our loss function
        loss_mse = tf.losses.mean_squared_error(targets, predictions) 
    
    if mode == learn.ModeKeys.TRAIN:
        # =====OPTIMIZER PARAMS========
        # now let's setup how we want thing to optimize 
        train_op = layers.optimize_loss(
            loss=loss_mse, 
            global_step=tf.contrib.framework.get_global_step(),
            optimizer='Adagrad', # adaptive gradient, so that the learning rate is not SO important 
            learning_rate=0.1)
    
    # what format to have the output in when calling clf.predict?
    predictions_out = predictions>0.5
    
    return model_fn_lib.ModelFnOps(
      mode=mode, predictions={'incomes':predictions_out}, loss=loss_mse, train_op=train_op)


In [99]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score

from sklearn.model_selection import StratifiedShuffleSplit

sss = StratifiedShuffleSplit(n_splits=5, test_size=0.5)

#df = df_train.ix[:1000].copy()
df = df_train.copy()

X = df.drop('income', axis=1).values
y = df['income'].values


# High cost for false negatives on "> 50,000" class

def weighted_recall_score(y_true, y_pred):
    """
    Weight determined by class imbalance
    """
    conf_matrix = confusion_matrix(y_true, y_pred)
    counts = np.bincount(y_true)
    weight = int(1 / (min(counts) / (sum(counts))))
    
    weight_matrix = np.array([
        [0, weight],
        [1, 0]
    ])
                 
    tp = np.sum(np.diagonal(conf_matrix))
    fn = np.sum(weight_matrix * conf_matrix)

    return tp / (tp + fn)

In [100]:
%%time

for train_index, test_index in sss.split(X, y):
    clf = learn.Estimator(model_fn=MLP)

    # when we provide the process function, they expect us to control the mini-batch
    clf.fit(input_fn=
                lambda:process_input(df.iloc[train_index], 'income',categorical_labels, continuous_labels), 
                steps=500)
    
    y_test = df['income'].iloc[test_index]

    yhat = clf.predict(input_fn=
                       lambda:process_input(df.iloc[test_index], None,categorical_labels, continuous_labels))
    # the output is now an iterable value, so we need to step over it
    yhat = [x['incomes'] for x in yhat]
    print(confusion_matrix(y_test,yhat),
          weighted_recall_score(y_test,yhat))

[[  719  2020]
 [  247 44579]] 0.567040120173
[[  820  1919]
 [  260 44566]] 0.579871979967
[[  764  1975]
 [  249 44577]] 0.572740478747
[[  774  1966]
 [  241 44584]] 0.573999316637
[[  751  1988]
 [  260 44566]] 0.570937220465
CPU times: user 1h 41min 33s, sys: 14min 16s, total: 1h 55min 49s
Wall time: 17min 3s


## Cross Columns

In [125]:
# https://www.tensorflow.org/tutorials/wide_and_deep
def process_input_cc(df, label_header, categ_headers, numeric_headers):
    # input: what ever you need it to be
    # output: (dict of feature columns as tensors), (labels as tensors)
    
    # ========Process Inputs=========
    # not much changes here, except we leave the numerics as tc.constants
    continuous_cols = {k: tf.constant(df[k].values) for k in numeric_headers}
      
    # and we shift these tensors to be sparse one-hot encoded values
    # Creates a dictionary mapping from each categorical feature column name (k)
    # to the values of that column stored in a tf.SparseTensor.
    categorical_cols = {k: tf.SparseTensor(
                              indices=[[i, 0] for i in range(df[k].size)],
                              values=df[k].values,
                              dense_shape=[df[k].size, 1])
                        for k in categ_headers}
    
    # Merges the two dictionaries into one.
    feature_cols = dict(categorical_cols)
    feature_cols.update(continuous_cols)
    
    # Convert the label column into a constant Tensor.
    label = None
    if label_header is not None:
        label = tf.constant(df[label_header].values)
        
    return feature_cols, label

In [126]:
process_input_cc(df_train,'income',categorical_labels, continuous_labels)

({'age': <tf.Tensor 'Const_216:0' shape=(95130,) dtype=float32>,
  'capital gains': <tf.Tensor 'Const_218:0' shape=(95130,) dtype=float32>,
  'capital losses': <tf.Tensor 'Const_219:0' shape=(95130,) dtype=float32>,
  'citizenship': <tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7f72e6d44358>,
  'class of worker': <tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7f731c6616a0>,
  'country of birth father': <tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7f731c655908>,
  'country of birth mother': <tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7f731c6556d8>,
  'country of birth self': <tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7f72e6d44860>,
  'detailed household and family stat': <tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7f732dec2080>,
  'detailed household summary in household': <tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7f732dec25c0>,
  'dividends from stocks': <tf.Tensor 'Const

In [127]:
# update the model to take input features as a dictionary
def setup_wide_deep_columns():
    # the prototype for this function is as follows
    # input:  (features, targets) 
    # output: (predictions, loss, train_op)
    
    wide_columns = []
    deep_columns = []
    # add in each of the categorical columns to both wide and deep features
    for col in categorical_labels:
        wide_columns.append(
            layers.sparse_column_with_keys(col, keys=labels[col])
        )
        
        dim = round(np.log2(len(labels[col])))
        deep_columns.append(
            layers.embedding_column(wide_columns[-1], dimension=dim)
        )
        
    # also add in some specific crossed columns
    cross_columns = [('education','occupation code'),('country of birth father', 'country of birth mother')]
    for tup in cross_columns:
        wide_columns.append(
            layers.crossed_column(
                [layers.sparse_column_with_keys(tup[0], keys=labels[tup[0]]),
                 layers.sparse_column_with_keys(tup[1], keys=labels[tup[1]])],
            hash_bucket_size=int(1e4))
        )
        
        
    # and add in the regular dense features 
    for col in continuous_labels:
        deep_columns.append(
            layers.real_valued_column(col)
        )
                    
    return wide_columns, deep_columns

In [129]:
tf.logging.set_verbosity(tf.logging.ERROR)

df = df_train.ix[:1000].copy()
#df = df_train.copy()

X = df.drop('income', axis=1).values
y = df['income'].values

wide_columns, deep_columns = setup_wide_deep_columns()

for train_index, test_index in sss.split(X, y):
    clf = learn.DNNLinearCombinedClassifier(
                            linear_feature_columns=wide_columns,
                            dnn_feature_columns=deep_columns,
                            dnn_hidden_units=[100, 50])
    
    #clf = learn.LinearClassifier(feature_columns=wide_columns)

    input_wrapper = lambda:process_input(df.iloc[train_index],'income',categorical_labels, continuous_labels)
    output_wrapper = lambda:process_input(df.iloc[test_index],None,categorical_labels, continuous_labels)

    # when we provide the process function, they expect us to control the mini-batch
    clf.fit(input_fn=input_wrapper, steps=500)

    y_test = df['income'].iloc[test_index]

    yhat = clf.predict(input_fn=output_wrapper)

    # the output is now an iterable value, so we need to step over it
    yhat = [x for x in yhat]

    print(confusion_matrix(y_test,yhat),
          weighted_recall_score(y_test,yhat))

ValueError: 'fill inc questionnaire for veteran's admin_embedding' is not a valid scope name

## Modeling (50 points total)
   
### [20 points] Create a combined wide and deep network to classify your data using tensorflow.
   
### [20 points] Investigate generalization performance by altering the number of layers. Try at least two different deep network architectures. Use the method of cross validation and evaluation metric that you argued for at the beginning of the lab.

### 10 points] Compare the performance of your best wide and deep network to a standard multi-layer perceptron (MLP) using the receiver operating characteristic and area under the curve.
___

## Exceptional Work (10 points total)
   
### One idea: Investigate which cross-product features are most important and hypothesize why.
___